import { Inter, Roboto_Mono  } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });
const roboto_mono = Roboto_Mono ({
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const combinedClassName = `${inter.className} ${roboto_mono.className}`;
  return (
    <html lang="en">
      <body className={combinedClassName}><div className="container">
          <Navbar />
          {children}
          <Footer />
        </div></body>
    </html>
  );
}
